#!/usr/bin/env bash
set -euo pipefail

# setup-safe-sink.sh — Phase 5: investigate (and optionally install, reversibly)
# an "AuraBridge Safe Sink": a virtual PipeWire sink that applies a FIXED-GAIN
# hard cap before audio reaches the physical output. This is the real, graph-level
# protection that polling (volume-guard-loop.sh) is NOT. See docs/safe-sink.md
# and docs/volume-safety.md.
#
# IMPORTANT HONESTY RULES:
#   - This script NEVER marks the Safe Sink "verified". Only test-safe-sink.sh,
#     plus a human confirming the 100%-volume danger question, can do that.
#   - DLNA stays blocked until that verification exists.
#   - It uses a PipeWire filter-chain config (NOT WirePlumber policy), so it does
#     not depend on the WirePlumber 0.4 vs 0.5 config model. No WirePlumber
#     policy is written here.
#   - It never routes to ALSA hw:/plughw:. The downstream device is referenced
#     by its dynamically detected PipeWire sink NAME, never a hardcoded card
#     number.
#   - The downstream device is whatever output is currently SELECTED
#     (scripts/select-output.sh): the USB DAC dongle (小尾巴 / KA11) or the Pi's
#     onboard 3.5 mm AUX. The Safe Sink follows that selection automatically.
#
# Modes:
#   (default)    investigate: read-only probe + write a DISABLED candidate config
#                (".conf.disabled", which PipeWire does NOT load). No live change.
#   --apply      activate the candidate config, restart the user PipeWire stack
#                with AUTO-ROLLBACK if the Safe Sink does not appear, and make it
#                the default sink. Still NOT "verified".
#   --rollback   deactivate the Safe Sink config, restore backups, restart.
#   --help
#
# Env:
#   SAFE_SINK_GAIN   linear output gain / hard cap (default 1.30)
#   ASSUME_YES=1     skip the interactive restart confirmation

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/output-target.sh
. "$SCRIPT_DIR/lib/output-target.sh"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$REPO_ROOT/logs"
SS_MARKER="$LOG_DIR/safe-sink-verified.txt"
PW_CONF_DIR="${HOME}/.config/pipewire/pipewire.conf.d"
CONF_NAME="99-aurabridge-safe-sink.conf"
CONF_PATH="${PW_CONF_DIR}/${CONF_NAME}"
CONF_DISABLED="${CONF_PATH}.disabled"

verified_marker_gain() {
  [[ -r "$SS_MARKER" ]] || return 0
  grep -q '^SAFE_SINK_VERIFIED=yes' "$SS_MARKER" 2>/dev/null || return 0
  sed -nE 's/^gain=([0-9]+([.][0-9]+)?).*/\1/p' "$SS_MARKER" 2>/dev/null | tail -n1
}

active_config_gain() {
  [[ -r "$CONF_PATH" ]] || return 0
  sed -nE 's/.*"mult"[[:space:]]*=[[:space:]]*([0-9]+([.][0-9]+)?).*/\1/p' "$CONF_PATH" 2>/dev/null | head -n1
}

SAFE_SINK_GAIN="${SAFE_SINK_GAIN:-$(active_config_gain)}"
SAFE_SINK_GAIN="${SAFE_SINK_GAIN:-$(verified_marker_gain)}"
SAFE_SINK_GAIN="${SAFE_SINK_GAIN:-1.30}"
SINK_NODE_NAME="aurabridge_safe_sink"
SINK_DESC="AuraBridge Safe Sink"

BOOT_REFRESH_UNIT="aurabridge-safe-sink-refresh.service"

log()  { printf '[safe-sink] %s\n' "$*"; }
warn() { printf '[safe-sink][WARN] %s\n' "$*" >&2; }
die()  { printf '[safe-sink][ERROR] %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

MODE="investigate"
case "${1:-}" in
  ""|investigate) MODE="investigate" ;;
  --apply)        MODE="apply" ;;
  --rollback)     MODE="rollback" ;;
  -h|--help)
    grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'
    exit 0 ;;
  *) die "Unknown argument '$1'. Use: (no arg) | --apply | --rollback | --help" ;;
esac

mkdir -p "$LOG_DIR"

# Find the downstream physical sink NAME (column 2 of `pactl list sinks short`)
# for whatever output is currently SELECTED (onboard AUX or USB dongle). Never a
# hardcoded card number; matched by name via scripts/lib/output-target.sh.
detect_target_sink() {
  have pactl || return 0
  detect_output_sink
}

# Emit the filter-chain config to stdout. $1 = downstream sink name, $2 = gain.
emit_config() {
  local target="$1" gain="$2"
  cat <<EOF
# AuraBridge Safe Sink — PipeWire filter-chain (fixed-gain hard cap).
# Generated by scripts/setup-safe-sink.sh. PipeWire config (NOT WirePlumber
# policy). Remove this file (or run setup-safe-sink.sh --rollback) and restart
# PipeWire to undo. The fixed linear gain ${gain} caps the MAXIMUM level sent to
# the physical output even if a client sets its own volume to 100%.
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "${SINK_DESC}"
      media.name       = "${SINK_DESC}"
      filter.graph = {
        nodes = [
          { type = builtin label = linear name = gainL control = { "mult" = ${gain} "add" = 0.0 } }
          { type = builtin label = linear name = gainR control = { "mult" = ${gain} "add" = 0.0 } }
        ]
        inputs  = [ "gainL:In" "gainR:In" ]
        outputs = [ "gainL:Out" "gainR:Out" ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name   = "${SINK_NODE_NAME}"
        media.class = Audio/Sink
      }
      playback.props = {
        node.name    = "${SINK_NODE_NAME}.output"
        node.passive = true
        target.object = "${target}"
      }
    }
  }
]
EOF
}

# ---------------------------------------------------------------------------
# PROBE (read-only) — always runs.
# ---------------------------------------------------------------------------
probe() {
  local ts; ts="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo unknown)"
  local plog="$LOG_DIR/safe-sink-setup-${ts}.txt"

  {
    echo "=== AuraBridge Safe Sink probe ($(date 2>/dev/null || echo no-date)) ==="
    echo
    echo "--- Versions ---"
    if have pipewire;    then echo "pipewire:    $(pipewire --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1)"; else echo "pipewire:    (not installed)"; fi
    if have wireplumber; then echo "wireplumber: $(wireplumber --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1)"; else echo "wireplumber: (not installed)"; fi
    echo
    echo "--- wpctl status ---"
    if have wpctl; then wpctl status 2>&1 || echo "(wpctl could not reach a PipeWire session)"; else echo "(wpctl not available)"; fi
    echo
    echo "--- pw-cli ls Node ---"
    if have pw-cli; then pw-cli ls Node 2>&1 || echo "(pw-cli ls Node failed)"; else echo "(pw-cli not available)"; fi
    echo
    echo "--- Downstream physical sink detection ---"
    echo "Selected output: $(output_effective_target) — $(describe_output_target)"
    local k; k="$(detect_target_sink)"
    if [[ -n "$k" ]]; then echo "Detected target sink name: ${k}"; else echo "Target sink NOT detected (run ./scripts/check-output.sh)"; fi
    echo
    echo "--- filter-chain module availability ---"
    if ls /usr/lib/*/pipewire-0.3/libpipewire-module-filter-chain.so >/dev/null 2>&1; then
      echo "filter-chain module present:"
      ls /usr/lib/*/pipewire-0.3/libpipewire-module-filter-chain.so 2>/dev/null
    else
      echo "(filter-chain .so not found by glob; it usually ships with PipeWire core)"
    fi
    echo
    echo "--- LADSPA plugin directories ---"
    ls /usr/lib/*/ladspa 2>/dev/null || ls /usr/lib/ladspa 2>/dev/null || echo "(no LADSPA directory found)"
    echo
    echo "--- LV2 plugin directories ---"
    ls /usr/lib/*/lv2 2>/dev/null || ls /usr/lib/lv2 2>/dev/null || echo "(no LV2 directory found)"
  } | tee "$plog"

  echo
  log "Probe written to: ${plog}"
}

feasible_or_reason() {
  # echoes "ok" or a human reason string
  if ! have pipewire; then echo "PipeWire is not installed"; return; fi
  if ! have pactl;    then echo "pactl (pulseaudio-utils) is not available"; return; fi
  local k; k="$(detect_target_sink)"
  if [[ -z "$k" ]]; then echo "the selected output sink could not be detected (run check-output.sh)"; return; fi
  echo "ok"
}

# ---------------------------------------------------------------------------
# INVESTIGATE (default): probe + write a DISABLED candidate config. No live change.
# ---------------------------------------------------------------------------
cmd_investigate() {
  log "Mode: investigate (read-only probe; writes a DISABLED candidate config only)."
  probe
  echo
  local reason; reason="$(feasible_or_reason)"
  local target; target="$(detect_target_sink)"
  mkdir -p "$PW_CONF_DIR"
  emit_config "${target:-REPLACE_WITH_OUTPUT_SINK_NAME}" "$SAFE_SINK_GAIN" > "$CONF_DISABLED"
  log "Wrote DISABLED candidate config: ${CONF_DISABLED}"
  log "(PipeWire does NOT load a .disabled file, so nothing changed in the audio graph.)"
  echo
  if [[ "$reason" == "ok" ]]; then
    log "A fixed-gain Safe Sink looks feasible (target sink: ${target}, gain ${SAFE_SINK_GAIN})."
    log "To install it REVERSIBLY on the Pi:   ./scripts/setup-safe-sink.sh --apply"
  else
    warn "A Safe Sink is NOT clearly feasible yet: ${reason}."
    warn "Resolve that first. Not applying anything."
  fi
  echo
  warn "Real-time audio safety layer NOT verified. DLNA must remain disabled."
  warn "After --apply, run ./scripts/test-safe-sink.sh on the Pi to verify."
}

# ---------------------------------------------------------------------------
# APPLY: activate config, restart PipeWire with auto-rollback, set as default.
# ---------------------------------------------------------------------------
restart_pw() {
  systemctl --user restart pipewire pipewire-pulse wireplumber 2>/dev/null \
    || systemctl --user restart pipewire wireplumber 2>/dev/null \
    || warn "Could not restart the user PipeWire stack via systemd."
}

install_boot_refresh_unit() {
  [[ "${AURABRIDGE_SAFE_SINK_SKIP_ENABLE:-0}" == "1" ]] && return 0
  local unit_src="$REPO_ROOT/systemd/${BOOT_REFRESH_UNIT}"
  local unit_dst="${HOME}/.config/systemd/user/${BOOT_REFRESH_UNIT}"
  [[ -f "$unit_src" ]] || { warn "Boot refresh unit missing from repo: ${unit_src}"; return 0; }
  mkdir -p "$(dirname "$unit_dst")"
  install -m 0644 "$unit_src" "$unit_dst"
  systemctl --user daemon-reload 2>/dev/null || warn "Could not reload user systemd after installing ${BOOT_REFRESH_UNIT}."
  if systemctl --user enable "$BOOT_REFRESH_UNIT" >/dev/null 2>&1; then
    log "Enabled boot refresh unit: ${BOOT_REFRESH_UNIT}"
  else
    warn "Could not enable ${BOOT_REFRESH_UNIT}. Run manually: systemctl --user enable ${BOOT_REFRESH_UNIT}"
  fi
}

cmd_apply() {
  have pipewire || die "PipeWire is not installed. Run ./scripts/setup-pipewire.sh first."
  have pactl    || die "pactl not available. Install pulseaudio-utils (setup-pipewire.sh)."
  local reason; reason="$(feasible_or_reason)"
  [[ "$reason" == "ok" ]] || die "Cannot apply: ${reason}."

  local target; target="$(detect_target_sink)"
  log "Target sink: ${target} ($(output_effective_target))  |  Safe Sink: ${SINK_NODE_NAME}  |  fixed gain: ${SAFE_SINK_GAIN}"
  echo
  warn "Applying the Safe Sink RESTARTS your PipeWire stack — active AirPlay /"
  warn "Spotify / Bluetooth streams will drop for a moment. This is reversible"
  warn "(./scripts/setup-safe-sink.sh --rollback)."
  if [[ "${ASSUME_YES:-0}" != "1" && -t 0 ]]; then
    local yn; read -r -p "Proceed with --apply? [y/N]: " yn || yn=""
    [[ "$yn" =~ ^[Yy]$ ]] || die "Aborted by user. Nothing changed."
  fi

  mkdir -p "$PW_CONF_DIR"
  # Remember current default sink so we can restore it on rollback.
  local prev_default; prev_default="$(pactl get-default-sink 2>/dev/null || echo "")"
  local ts; ts="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo unknown)"

  # Back up any pre-existing real config with this name.
  if [[ -f "$CONF_PATH" ]]; then
    cp -a "$CONF_PATH" "${CONF_PATH}.bak.${ts}"
    log "Backed up existing ${CONF_NAME} -> ${CONF_PATH}.bak.${ts}"
  fi

  emit_config "$target" "$SAFE_SINK_GAIN" > "$CONF_PATH"
  log "Activated config: ${CONF_PATH}"

  log "Restarting the user PipeWire stack..."
  restart_pw
  sleep 3

  # Verify the Safe Sink appeared; otherwise AUTO-ROLLBACK.
  if pactl list sinks short 2>/dev/null | grep -q "$SINK_NODE_NAME"; then
    log "Safe Sink '${SINK_NODE_NAME}' is present."
  else
    warn "Safe Sink did NOT appear after restart — auto-rolling back to protect audio."
    rm -f "$CONF_PATH"
    if [[ -f "${CONF_PATH}.bak.${ts}" ]]; then mv -f "${CONF_PATH}.bak.${ts}" "$CONF_PATH"; fi
    restart_pw
    sleep 2
    [[ -n "$prev_default" ]] && pactl set-default-sink "$prev_default" 2>/dev/null || true
    die "Apply failed and was rolled back. Check 'journalctl --user -u pipewire' and the config."
  fi

  # Route normal clients to the Safe Sink (the physical output stays present but non-default).
  if pactl set-default-sink "$SINK_NODE_NAME" 2>/dev/null; then
    log "Default sink set to '${SINK_NODE_NAME}' (the physical output is no longer the default)."
  else
    warn "Could not set the default sink. Set it manually: pactl set-default-sink ${SINK_NODE_NAME}"
  fi

  # Re-assert a safe INITIAL volume on the new default sink.
  if [[ -x "$SCRIPT_DIR/safe-volume.sh" ]]; then
    "$SCRIPT_DIR/safe-volume.sh" || warn "safe-volume.sh reported an issue (continuing)."
  fi

  install_boot_refresh_unit

  echo
  local marker_gain; marker_gain="$(verified_marker_gain)"
  if [[ -n "$marker_gain" && "$marker_gain" == "$SAFE_SINK_GAIN" ]]; then
    log "Safe Sink applied (fixed-gain ${SAFE_SINK_GAIN}). Existing verification marker matches this gain."
  elif [[ -n "$marker_gain" ]]; then
    log "Safe Sink applied (fixed-gain ${SAFE_SINK_GAIN})."
    warn "Existing verification marker is for gain ${marker_gain}, not ${SAFE_SINK_GAIN}; re-verify before treating DLNA as safe."
  else
    log "Safe Sink applied (fixed-gain ${SAFE_SINK_GAIN}). This is INSTALLED but NOT VERIFIED."
    warn "Real-time audio safety layer NOT verified. DLNA must remain disabled."
  fi
  log "Verify on the Pi now:   ./scripts/test-safe-sink.sh"
  log "Roll back at any time:  ./scripts/setup-safe-sink.sh --rollback"
}

# ---------------------------------------------------------------------------
# ROLLBACK: deactivate the Safe Sink config and restart.
# ---------------------------------------------------------------------------
cmd_rollback() {
  local did=0
  if [[ -f "$CONF_PATH" ]]; then
    local ts; ts="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo unknown)"
    mv -f "$CONF_PATH" "${CONF_PATH}.removed.${ts}"
    log "Removed active config -> ${CONF_PATH}.removed.${ts}"
    did=1
  else
    log "No active Safe Sink config (${CONF_PATH}) found."
  fi
  if have systemctl; then
    log "Restarting the user PipeWire stack..."
    restart_pw
    sleep 2
  fi
  # The physical sink should become selectable again; let WirePlumber pick a default.
  if [[ "$did" -eq 1 ]]; then
    log "Rolled back. Confirm with: ./scripts/status.sh and ./scripts/check-output.sh"
  fi
  warn "Safe Sink removed -> DLNA must remain disabled (it was already blocked)."
}

case "$MODE" in
  investigate) cmd_investigate ;;
  apply)       cmd_apply ;;
  rollback)    cmd_rollback ;;
esac
