#!/usr/bin/env bash
set -euo pipefail

# setup-safe-sink.sh — Phase 5: investigate (and optionally install, reversibly)
# an "AuraBridge Safe Sink": a virtual PipeWire sink that applies a FIXED-GAIN
# hard cap before audio reaches the FiiO KA11. This is the real, graph-level
# protection that polling (volume-guard-loop.sh) is NOT. See docs/safe-sink.md
# and docs/volume-safety.md.
#
# IMPORTANT HONESTY RULES:
#   - This script NEVER marks the Safe Sink "verified". Only test-safe-sink.sh,
#     plus a human confirming the 100%-volume danger question, can do that.
#   - DLNA stays blocked until that verification exists.
#   - It uses a PipeWire filter-chain config (NOT WirePlumber policy), so it does
#     not depend on the WirePlumber 0.4 vs 0.5 config model. No WirePlumber
#     policy is written here.
#   - It never routes to ALSA hw:/plughw:. The KA11 is referenced by its
#     dynamically detected PipeWire sink NAME, never a hardcoded card number.
#
# Modes:
#   (default)    investigate: read-only probe + write a DISABLED candidate config
#                (".conf.disabled", which PipeWire does NOT load). No live change.
#   --apply      activate the candidate config, restart the user PipeWire stack
#                with AUTO-ROLLBACK if the Safe Sink does not appear, and make it
#                the default sink. Still NOT "verified".
#   --rollback   deactivate the Safe Sink config, restore backups, restart.
#   --help
#
# Env:
#   SAFE_SINK_GAIN   linear output gain / hard cap (default 0.40 ~= -8 dB)
#   ASSUME_YES=1     skip the interactive restart confirmation

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$REPO_ROOT/logs"
SAFE_SINK_GAIN="${SAFE_SINK_GAIN:-0.40}"
SINK_NODE_NAME="aurabridge_safe_sink"
SINK_DESC="AuraBridge Safe Sink"

PW_CONF_DIR="${HOME}/.config/pipewire/pipewire.conf.d"
CONF_NAME="99-aurabridge-safe-sink.conf"
CONF_PATH="${PW_CONF_DIR}/${CONF_NAME}"
CONF_DISABLED="${CONF_PATH}.disabled"

log()  { printf '[safe-sink] %s\n' "$*"; }
warn() { printf '[safe-sink][WARN] %s\n' "$*" >&2; }
die()  { printf '[safe-sink][ERROR] %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

MODE="investigate"
case "${1:-}" in
  ""|investigate) MODE="investigate" ;;
  --apply)        MODE="apply" ;;
  --rollback)     MODE="rollback" ;;
  -h|--help)
    grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'
    exit 0 ;;
  *) die "Unknown argument '$1'. Use: (no arg) | --apply | --rollback | --help" ;;
esac

mkdir -p "$LOG_DIR"

# Find the KA11 / USB-DAC PipeWire sink NAME (column 2 of `pactl list sinks short`).
# Never a hardcoded card number; matched by name, like check-ka11.sh.
KA11_HINTS='fiio|ka11|usb audio|usb-audio|\bdac\b|headphone|usb dac'
detect_ka11_sink() {
  have pactl || return 0
  pactl list sinks short 2>/dev/null \
    | grep -iE "$KA11_HINTS" \
    | grep -ivE 'aurabridge|safe.?sink' \
    | awk '{print $2}' \
    | head -n1
}

# Emit the filter-chain config to stdout. $1 = KA11 sink name, $2 = gain.
emit_config() {
  local ka11="$1" gain="$2"
  cat <<EOF
# AuraBridge Safe Sink — PipeWire filter-chain (fixed-gain hard cap).
# Generated by scripts/setup-safe-sink.sh. PipeWire config (NOT WirePlumber
# policy). Remove this file (or run setup-safe-sink.sh --rollback) and restart
# PipeWire to undo. The fixed linear gain ${gain} caps the MAXIMUM level sent to
# the KA11 even if a client sets its own volume to 100%.
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "${SINK_DESC}"
      media.name       = "${SINK_DESC}"
      filter.graph = {
        nodes = [
          { type = builtin label = linear name = gainL control = { "mult" = ${gain} "add" = 0.0 } }
          { type = builtin label = linear name = gainR control = { "mult" = ${gain} "add" = 0.0 } }
        ]
        inputs  = [ "gainL:In" "gainR:In" ]
        outputs = [ "gainL:Out" "gainR:Out" ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name   = "${SINK_NODE_NAME}"
        media.class = Audio/Sink
      }
      playback.props = {
        node.name    = "${SINK_NODE_NAME}.output"
        node.passive = true
        target.object = "${ka11}"
      }
    }
  }
]
EOF
}

# ---------------------------------------------------------------------------
# PROBE (read-only) — always runs.
# ---------------------------------------------------------------------------
probe() {
  local ts; ts="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo unknown)"
  local plog="$LOG_DIR/safe-sink-setup-${ts}.txt"

  {
    echo "=== AuraBridge Safe Sink probe ($(date 2>/dev/null || echo no-date)) ==="
    echo
    echo "--- Versions ---"
    if have pipewire;    then echo "pipewire:    $(pipewire --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1)"; else echo "pipewire:    (not installed)"; fi
    if have wireplumber; then echo "wireplumber: $(wireplumber --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1)"; else echo "wireplumber: (not installed)"; fi
    echo
    echo "--- wpctl status ---"
    if have wpctl; then wpctl status 2>&1 || echo "(wpctl could not reach a PipeWire session)"; else echo "(wpctl not available)"; fi
    echo
    echo "--- pw-cli ls Node ---"
    if have pw-cli; then pw-cli ls Node 2>&1 || echo "(pw-cli ls Node failed)"; else echo "(pw-cli not available)"; fi
    echo
    echo "--- KA11 physical sink detection ---"
    local k; k="$(detect_ka11_sink)"
    if [[ -n "$k" ]]; then echo "Detected KA11 sink name: ${k}"; else echo "KA11 sink NOT detected (run ./scripts/check-ka11.sh)"; fi
    echo
    echo "--- filter-chain module availability ---"
    if ls /usr/lib/*/pipewire-0.3/libpipewire-module-filter-chain.so >/dev/null 2>&1; then
      echo "filter-chain module present:"
      ls /usr/lib/*/pipewire-0.3/libpipewire-module-filter-chain.so 2>/dev/null
    else
      echo "(filter-chain .so not found by glob; it usually ships with PipeWire core)"
    fi
    echo
    echo "--- LADSPA plugin directories ---"
    ls /usr/lib/*/ladspa 2>/dev/null || ls /usr/lib/ladspa 2>/dev/null || echo "(no LADSPA directory found)"
    echo
    echo "--- LV2 plugin directories ---"
    ls /usr/lib/*/lv2 2>/dev/null || ls /usr/lib/lv2 2>/dev/null || echo "(no LV2 directory found)"
  } | tee "$plog"

  echo
  log "Probe written to: ${plog}"
}

feasible_or_reason() {
  # echoes "ok" or a human reason string
  if ! have pipewire; then echo "PipeWire is not installed"; return; fi
  if ! have pactl;    then echo "pactl (pulseaudio-utils) is not available"; return; fi
  local k; k="$(detect_ka11_sink)"
  if [[ -z "$k" ]]; then echo "the KA11 sink could not be detected (run check-ka11.sh)"; return; fi
  echo "ok"
}

# ---------------------------------------------------------------------------
# INVESTIGATE (default): probe + write a DISABLED candidate config. No live change.
# ---------------------------------------------------------------------------
cmd_investigate() {
  log "Mode: investigate (read-only probe; writes a DISABLED candidate config only)."
  probe
  echo
  local reason; reason="$(feasible_or_reason)"
  local ka11; ka11="$(detect_ka11_sink)"
  mkdir -p "$PW_CONF_DIR"
  emit_config "${ka11:-REPLACE_WITH_KA11_SINK_NAME}" "$SAFE_SINK_GAIN" > "$CONF_DISABLED"
  log "Wrote DISABLED candidate config: ${CONF_DISABLED}"
  log "(PipeWire does NOT load a .disabled file, so nothing changed in the audio graph.)"
  echo
  if [[ "$reason" == "ok" ]]; then
    log "A fixed-gain Safe Sink looks feasible (KA11 sink: ${ka11}, gain ${SAFE_SINK_GAIN})."
    log "To install it REVERSIBLY on the Pi:   ./scripts/setup-safe-sink.sh --apply"
  else
    warn "A Safe Sink is NOT clearly feasible yet: ${reason}."
    warn "Resolve that first. Not applying anything."
  fi
  echo
  warn "Real-time audio safety layer NOT verified. DLNA must remain disabled."
  warn "After --apply, run ./scripts/test-safe-sink.sh on the Pi to verify."
}

# ---------------------------------------------------------------------------
# APPLY: activate config, restart PipeWire with auto-rollback, set as default.
# ---------------------------------------------------------------------------
restart_pw() {
  systemctl --user restart pipewire pipewire-pulse wireplumber 2>/dev/null \
    || systemctl --user restart pipewire wireplumber 2>/dev/null \
    || warn "Could not restart the user PipeWire stack via systemd."
}

cmd_apply() {
  have pipewire || die "PipeWire is not installed. Run ./scripts/setup-pipewire.sh first."
  have pactl    || die "pactl not available. Install pulseaudio-utils (setup-pipewire.sh)."
  local reason; reason="$(feasible_or_reason)"
  [[ "$reason" == "ok" ]] || die "Cannot apply: ${reason}."

  local ka11; ka11="$(detect_ka11_sink)"
  log "KA11 sink: ${ka11}  |  Safe Sink: ${SINK_NODE_NAME}  |  fixed gain: ${SAFE_SINK_GAIN}"
  echo
  warn "Applying the Safe Sink RESTARTS your PipeWire stack — active AirPlay /"
  warn "Spotify / Bluetooth streams will drop for a moment. This is reversible"
  warn "(./scripts/setup-safe-sink.sh --rollback)."
  if [[ "${ASSUME_YES:-0}" != "1" && -t 0 ]]; then
    local yn; read -r -p "Proceed with --apply? [y/N]: " yn || yn=""
    [[ "$yn" =~ ^[Yy]$ ]] || die "Aborted by user. Nothing changed."
  fi

  mkdir -p "$PW_CONF_DIR"
  # Remember current default sink so we can restore it on rollback.
  local prev_default; prev_default="$(pactl get-default-sink 2>/dev/null || echo "")"
  local ts; ts="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo unknown)"

  # Back up any pre-existing real config with this name.
  if [[ -f "$CONF_PATH" ]]; then
    cp -a "$CONF_PATH" "${CONF_PATH}.bak.${ts}"
    log "Backed up existing ${CONF_NAME} -> ${CONF_PATH}.bak.${ts}"
  fi

  emit_config "$ka11" "$SAFE_SINK_GAIN" > "$CONF_PATH"
  log "Activated config: ${CONF_PATH}"

  log "Restarting the user PipeWire stack..."
  restart_pw
  sleep 3

  # Verify the Safe Sink appeared; otherwise AUTO-ROLLBACK.
  if pactl list sinks short 2>/dev/null | grep -q "$SINK_NODE_NAME"; then
    log "Safe Sink '${SINK_NODE_NAME}' is present."
  else
    warn "Safe Sink did NOT appear after restart — auto-rolling back to protect audio."
    rm -f "$CONF_PATH"
    if [[ -f "${CONF_PATH}.bak.${ts}" ]]; then mv -f "${CONF_PATH}.bak.${ts}" "$CONF_PATH"; fi
    restart_pw
    sleep 2
    [[ -n "$prev_default" ]] && pactl set-default-sink "$prev_default" 2>/dev/null || true
    die "Apply failed and was rolled back. Check 'journalctl --user -u pipewire' and the config."
  fi

  # Route normal clients to the Safe Sink (KA11 stays present but non-default).
  if pactl set-default-sink "$SINK_NODE_NAME" 2>/dev/null; then
    log "Default sink set to '${SINK_NODE_NAME}' (KA11 is no longer the default)."
  else
    warn "Could not set the default sink. Set it manually: pactl set-default-sink ${SINK_NODE_NAME}"
  fi

  # Re-assert a safe INITIAL volume on the new default sink.
  if [[ -x "$SCRIPT_DIR/safe-volume.sh" ]]; then
    "$SCRIPT_DIR/safe-volume.sh" || warn "safe-volume.sh reported an issue (continuing)."
  fi

  echo
  log "Safe Sink applied (fixed-gain ${SAFE_SINK_GAIN}). This is INSTALLED but NOT VERIFIED."
  warn "Real-time audio safety layer NOT verified. DLNA must remain disabled."
  log "Verify on the Pi now:   ./scripts/test-safe-sink.sh"
  log "Roll back at any time:  ./scripts/setup-safe-sink.sh --rollback"
}

# ---------------------------------------------------------------------------
# ROLLBACK: deactivate the Safe Sink config and restart.
# ---------------------------------------------------------------------------
cmd_rollback() {
  local did=0
  if [[ -f "$CONF_PATH" ]]; then
    local ts; ts="$(date +%Y%m%d-%H%M%S 2>/dev/null || echo unknown)"
    mv -f "$CONF_PATH" "${CONF_PATH}.removed.${ts}"
    log "Removed active config -> ${CONF_PATH}.removed.${ts}"
    did=1
  else
    log "No active Safe Sink config (${CONF_PATH}) found."
  fi
  if have systemctl; then
    log "Restarting the user PipeWire stack..."
    restart_pw
    sleep 2
  fi
  # The KA11 sink should become selectable again; let WirePlumber pick a default.
  if [[ "$did" -eq 1 ]]; then
    log "Rolled back. Confirm with: ./scripts/status.sh and ./scripts/check-ka11.sh"
  fi
  warn "Safe Sink removed -> DLNA must remain disabled (it was already blocked)."
}

case "$MODE" in
  investigate) cmd_investigate ;;
  apply)       cmd_apply ;;
  rollback)    cmd_rollback ;;
esac
